[package]
name = "untitled-space-game"
version = "0.1.0"
authors = ["tylermaran <tyler.maran@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.21.0" }
